name: Release

on:
  push:
    branches:
      - main
    paths:
      - src/**
  workflow_dispatch:
    inputs:
      version:
        description: 'Version bump'
        required: true
        default: 'patch'
        type: choice
        options:
          - prerelease
          - prepatch
          - preminor
          - premajor
          - patch
          - minor
          - major


jobs:
  release:
    uses: drehelis/improved-chainsaw/.github/workflows/release.yml@main
    with:
      version: ${{ github.event.inputs.version || 'patch' }}
      pre_release_command: "bash ./scripts/update-data.sh"
      timeout_minutes: 5
    secrets: inherit